-- 2440060383 – Kevin Bennett Haryono
-- RebornE#5382


CREATE DATABASE theory_exam

USE theory_exam

CREATE TABLE Users(
	UserID CHAR(10),
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	Gender VARCHAR(10) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	UserAddress VARCHAR(255),
	PhoneNumber CHAR(12) NOT NULL,
	School VARCHAR(255),
	UserLocation VARCHAR(255),
	DateofBirth DATE,
	CONSTRAINT UserID_PK PRIMARY KEY(UserID),
	CONSTRAINT UserID_CHK CHECK(UserID LIKE 'U[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	CONSTRAINT Gender_CHK CHECK(Gender LIKE 'Male' OR Gender LIKE 'Female' OR Gender LIKE 'Other'),
	CONSTRAINT Email_CHK CHECK(Email LIKE '%_@__%.__%'),
	CONSTRAINT PhoneNumber_CHK CHECK(PhoneNumber NOT LIKE '%[^0-9]%')
)

CREATE TABLE Posts(
	PostID CHAR(10),
	UserID CHAR(10),
	PostContent VARCHAR(255) NOT NULL,
	PostDate DATE,
	CONSTRAINT PostID_PK PRIMARY KEY(PostID),
	CONSTRAINT PostID_CHK CHECK(PostID LIKE 'P[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	CONSTRAINT UserID_FK_Posts FOREIGN KEY(UserID) REFERENCES Users(UserID)
		ON UPDATE CASCADE ON DELETE SET NULL,
)

CREATE TABLE Photos(
	PhotoID CHAR(10),
	PostID CHAR(10),
	ImageContent VARCHAR(255) NOT NULL,
	CONSTRAINT PhotoID_PK PRIMARY KEY(PhotoID),
	CONSTRAINT PhotoID_CHK CHECK(PhotoID LIKE 'PH[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	CONSTRAINT PostID_FK_Photos FOREIGN KEY(PostID) REFERENCES Posts(PostID)
		ON UPDATE CASCADE ON DELETE SET NULL
)

CREATE TABLE Pages(
	PageID CHAR(10),
	PageName VARCHAR(255),
	PageContent VARCHAR(255) NOT NULL,
	CONSTRAINT PageID_PK PRIMARY KEY(PageID),
	CONSTRAINT PageID_CHK CHECK(PageID LIKE 'PG[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'), 
)

CREATE TABLE Comments(
	CommentID CHAR(10),
	PostID CHAR(10),
	UserID CHAR(10),
	CommentDate DATE,
	CommentContent VARCHAR(255) NOT NULL,
	CONSTRAINT CommentID_PK PRIMARY KEY(CommentID),
	CONSTRAINT CommentID_CHK CHECK(CommentID LIKE 'C[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	CONSTRAINT PostID_FK_Comments FOREIGN KEY(PostID) REFERENCES Posts(PostID)
		ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT UserID_FK_Comments FOREIGN KEY(UserID) REFERENCES Users(UserID)
		ON UPDATE NO ACTION ON DELETE NO ACTION
)

CREATE TABLE Friends(
	FriendID CHAR(10),
	UserID CHAR(10),
	CONSTRAINT FriendID_PK PRIMARY KEY(FriendID),
	CONSTRAINT UserID_FK_Friends FOREIGN KEY(UserID) REFERENCES Users(UserID)
		ON UPDATE CASCADE ON DELETE SET NULL,
)

CREATE TABLE PageLikes(
	UserID CHAR(10),
	PageID CHAR(10),
	PRIMARY KEY(UserID, PageID),
	FOREIGN KEY(UserID) REFERENCES Users(UserID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(PageID) REFERENCES Pages(PageID)
		ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE PostLikes(
	UserID CHAR(10),
	PostID CHAR(10),
	PRIMARY KEY(UserID, PostID),
	FOREIGN KEY(UserID) REFERENCES Users(UserID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(PostID) REFERENCES Posts(PostID)
		ON UPDATE NO ACTION ON DELETE NO ACTION
)

CREATE TABLE CommentLikes(
	UserID CHAR(10),
	CommentID CHAR(10),
	PRIMARY KEY(UserID, CommentID),
	FOREIGN KEY(UserID) REFERENCES Users(UserID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(CommentID) REFERENCES Comments(CommentID)
		ON UPDATE NO ACTION ON DELETE NO ACTION
)

CREATE TABLE Shares(
	UserID CHAR(10),
	PostID CHAR(10),
	PRIMARY KEY(UserID, PostID),
	FOREIGN KEY(UserID) REFERENCES Users(UserID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(PostID) REFERENCES Posts(PostID)
		ON UPDATE NO ACTION ON DELETE NO ACTION
)